/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.app.view;

import br.app.fabrica.FabricaCafe;
import br.app.fabrica.FabricaCappucino;
import br.app.fabrica.FabricaCha;
import br.app.fabrica.FabricaChocolate;
import br.app.interfaces.FabricaBebida;

/**
 *
 * @author mvictor
 */
public class Lanchonete extends javax.swing.JFrame {

    /**
     * Creates new form Lanchonete
     */
    public Lanchonete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncafe = new javax.swing.JButton();
        btncappucino = new javax.swing.JButton();
        btncha = new javax.swing.JButton();
        btnchocolate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Lanchonete", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btncafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cafe.png"))); // NOI18N
        btncafe.setBorderPainted(false);
        btncafe.setContentAreaFilled(false);
        btncafe.setFocusPainted(false);
        btncafe.setFocusable(false);
        btncafe.setRequestFocusEnabled(false);
        btncafe.setRolloverEnabled(false);
        btncafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncafeActionPerformed(evt);
            }
        });

        btncappucino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cappucino.png"))); // NOI18N
        btncappucino.setBorderPainted(false);
        btncappucino.setContentAreaFilled(false);
        btncappucino.setFocusPainted(false);
        btncappucino.setFocusable(false);
        btncappucino.setRequestFocusEnabled(false);
        btncappucino.setRolloverEnabled(false);
        btncappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncappucinoActionPerformed(evt);
            }
        });

        btncha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cha.png"))); // NOI18N
        btncha.setBorderPainted(false);
        btncha.setContentAreaFilled(false);
        btncha.setFocusPainted(false);
        btncha.setFocusable(false);
        btncha.setRequestFocusEnabled(false);
        btncha.setRolloverEnabled(false);
        btncha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchaActionPerformed(evt);
            }
        });

        btnchocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/chocolate.png"))); // NOI18N
        btnchocolate.setBorderPainted(false);
        btnchocolate.setContentAreaFilled(false);
        btnchocolate.setFocusPainted(false);
        btnchocolate.setFocusable(false);
        btnchocolate.setRequestFocusEnabled(false);
        btnchocolate.setRolloverEnabled(false);
        btnchocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchocolateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(btncappucino, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnchocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btncha, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(btncafe, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(336, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnchocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncha, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncappucino, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(btncafe, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        jLabel1.setText("Clique no item para efetuar a compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchocolateActionPerformed
        // TODO add your handling code here:
        FabricaBebida fabrica = new FabricaChocolate();
        Info info = new Info(
            fabrica.criarBebida().getNome(),
            fabrica.criarBebida().getIngredientes(),
            fabrica.criarBebida().getPreco()
        );
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnchocolateActionPerformed

    private void btncafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncafeActionPerformed
        // TODO add your handling code here:
        FabricaBebida fabrica = new FabricaCafe();
        Info info = new Info(
            fabrica.criarBebida().getNome(),
            fabrica.criarBebida().getIngredientes(),
            fabrica.criarBebida().getPreco()
        );
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncafeActionPerformed

    private void btncappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncappucinoActionPerformed
        // TODO add your handling code here:
        FabricaBebida fabrica = new FabricaCappucino();
        Info info = new Info(
            fabrica.criarBebida().getNome(),
            fabrica.criarBebida().getIngredientes(),
            fabrica.criarBebida().getPreco()
        );
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncappucinoActionPerformed

    private void btnchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchaActionPerformed
        // TODO add your handling code here:
        FabricaBebida fabrica = new FabricaCha();
        Info info = new Info(
            fabrica.criarBebida().getNome(),
            fabrica.criarBebida().getIngredientes(),
            fabrica.criarBebida().getPreco()
        );
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnchaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lanchonete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncafe;
    private javax.swing.JButton btncappucino;
    private javax.swing.JButton btncha;
    private javax.swing.JButton btnchocolate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
