/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bebidas.Cafe;
import br.app.mvictor.interfaces.Bebida;
import br.app.mvictor.interfaces.BebidaBase;
import br.app.mvictor.interfaces.IngredienteAdicional;

/**
 *
 * @author mvictor
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.txtdescricao.setEditable(false);
        this.txtpreco.setEditable(false);
        this.txtitems.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldescricao = new javax.swing.JLabel();
        lblpreco = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        choiceOpc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtitems = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbldescricao.setText("Descrição:");

        lblpreco.setText("Preço");

        choiceOpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Café Tradicional", "Café c/ Leite", "Chocolate", "Chá de Camomila", "Chá de Arruda", "Cappucino Tradicional", "Cappucino Plus", "Chá de Erva Doce", "Solvete", "Milkshake", "Café Gelado", "Chá Verde Gelado" }));
        choiceOpc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceOpcItemStateChanged(evt);
            }
        });
        choiceOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceOpcActionPerformed(evt);
            }
        });

        txtitems.setColumns(20);
        txtitems.setRows(5);
        jScrollPane1.setViewportView(txtitems);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbldescricao)
                    .addComponent(lblpreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtpreco, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(choiceOpc, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtdescricao)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescricao)
                    .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpreco)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButton1.setText("Comprar");

        jButton2.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choiceOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceOpcActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_choiceOpcActionPerformed

    private void choiceOpcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceOpcItemStateChanged
        // TODO add your handling code here:
        try{
            Bebida bebida;
            switch(this.choiceOpc.getSelectedItem().toString())
            {
                case "Café Tradicional":
                    Bebida cafeTradicional = new BebidaBase("Café ", 2.5);
                    cafeTradicional = new IngredienteAdicional(cafeTradicional,"Açucar", 0.5);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + cafeTradicional.getPreco());
                    txtitems.setText(cafeTradicional.getDescricao());
                    break;
                case "Café c/ Leite":
                    bebida = new BebidaBase("Café ", 2.5);
                    bebida= new IngredienteAdicional(bebida,"Açucar", 0.5);
                    bebida= new IngredienteAdicional(bebida,"Leite", 1.0);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Chocolate":
                    bebida = new BebidaBase("Chocolate ", 2.5);
                    bebida= new IngredienteAdicional(bebida,"Açucar", 0.5);
                    bebida= new IngredienteAdicional(bebida,"Leite", 1.0);
                    bebida= new IngredienteAdicional(bebida,"Canela", 1.0);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Chá de Camomila":
                    bebida = new BebidaBase("Camomila", 2.5);
                    bebida= new IngredienteAdicional(bebida,"Açucar", 0.01);
                    bebida= new IngredienteAdicional(bebida,"Água Quente", 0.0);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Chá de Arruda":
                    bebida = new BebidaBase("Arruda", 2.5);
                    bebida= new IngredienteAdicional(bebida,"Açucar", 0.02);
                    bebida= new IngredienteAdicional(bebida,"Água Quente", 0.0);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Cappucino Tradicional":
                    bebida = new BebidaBase("Chocolate ", 2.5);
                    bebida= new IngredienteAdicional(bebida,"Açucar", 0.5);
                    bebida= new IngredienteAdicional(bebida,"Leite", 1.0);
                    bebida= new IngredienteAdicional(bebida,"Café Descafeinado", 2.0);
                    bebida= new IngredienteAdicional(bebida,"Canela", 0.50);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Cappucino Plus":
                    bebida = new BebidaBase("Chocolate ", 2.5);
                    bebida= new IngredienteAdicional(bebida,"Açucar", 0.5);
                    bebida= new IngredienteAdicional(bebida,"Leite", 1.0);
                    bebida= new IngredienteAdicional(bebida,"Creme de Leite", 1.75);
                    bebida= new IngredienteAdicional(bebida,"Café Descafeinado", 2.0);
                    bebida= new IngredienteAdicional(bebida,"Canela", 0.50);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Chá de Erva Doce":
                    bebida = new BebidaBase("Erva Doce", 2.5);
                    bebida= new IngredienteAdicional(bebida,"Açucar", 0.02);
                    bebida= new IngredienteAdicional(bebida,"Água Quente", 0.0);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Solvete":
                    bebida = new BebidaBase("Solvete de Chocolate", 2.0);
                    bebida= new IngredienteAdicional(bebida,"Cobertura de Baunilha", 1.24);
                    bebida= new IngredienteAdicional(bebida,"Granulado", 2.75);
                    bebida= new IngredienteAdicional(bebida,"Leite em Pó", 1.21);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Milkshake":
                    bebida = new BebidaBase("Solvete de Chocolate", 2.0);
                    bebida= new IngredienteAdicional(bebida,"Creme de Leite", 1.30);
                    bebida= new IngredienteAdicional(bebida,"Leite Condesado", 1.20);
                    bebida= new IngredienteAdicional(bebida,"Chocolate", 1.24);
                    bebida= new IngredienteAdicional(bebida,"Cobertura de Baunilha", 1.24);
                    bebida= new IngredienteAdicional(bebida,"Granulado", 2.75);
                    bebida= new IngredienteAdicional(bebida,"Leite em Pó", 1.21);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Café Gelado":
                    bebida = new BebidaBase("Café", 2.5);
                    bebida= new IngredienteAdicional(bebida,"Canela", 0.25);
                    bebida= new IngredienteAdicional(bebida,"Gelo", 0.02);
                    bebida= new IngredienteAdicional(bebida,"Açucar", 0.02);
                    bebida= new IngredienteAdicional(bebida,"Água Gelada", 0.0);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                case "Chá Verde Gelado":
                    bebida = new BebidaBase("Verde", 2.5);
                    bebida= new IngredienteAdicional(bebida,"Cafeina", 2.0);
                    bebida= new IngredienteAdicional(bebida,"Creme de Leite", 2.0);
                    bebida= new IngredienteAdicional(bebida,"Gelo", 0.15);
                    bebida= new IngredienteAdicional(bebida,"Açucar", 0.30);
                    bebida= new IngredienteAdicional(bebida,"Água Gelada", 0);
                    txtdescricao.setText(choiceOpc.getSelectedItem().toString());
                    txtpreco.setText("R$: " + bebida.getPreco());
                    txtitems.setText(bebida.getDescricao());
                    break;
                default:
                    txtdescricao.setText(null);
                    txtpreco.setText(null);
                    txtitems.setText(null);
                    break;
            }
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_choiceOpcItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choiceOpc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldescricao;
    private javax.swing.JLabel lblpreco;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextArea txtitems;
    private javax.swing.JTextField txtpreco;
    // End of variables declaration//GEN-END:variables
}
